version: "3.3"

services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
#      DB_USERNAME: root
#      DB_PASSWORD: root
#      DATABASE_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://dbmysql:3306/hmsnew1?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - dbmysql
    networks:
      - submission-app
#      - backend
#      - frontend
  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
#    expose:
#      - "3000"
    ports:
#      - 3000:3000
       - 80:80
#    environment:
#      CHOKIDAR_USEPOLLING: "true"
#    volumes:
#      - ./front-end/node_modules:/usr/app/node_modules
#      - ./front-end:/usr/app
#       - webdata:/app/build/
    depends_on:
      - back-end
    networks:
      - submission-app
#      - frontend
  dbmysql:
    image: mysql:5.7
#    build:#
#      context: db
#      dockerfile: Dockerfile
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hmsnew1
      MYSQL_ROOT_PASSWORD: Mustakim@123
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

    networks:
      - submission-app
#      - backend
#  web-server:
#    image: nginx:1.21.6-alpine
#    ports:
#      - 80:80
#      - 443:443
#    depends_on:
#      - front-end
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./nginx/conf/:/etc/nginx/conf.d/:ro
#       - webdata:/usr/share/nginx/html/:ro
volumes:
  dbdata:
  webdata:
networks:
  submission-app:
#  backend:
#  frontend:
